/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as VocabRouteImport } from './routes/vocab'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabRoute = VocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/vocab': typeof VocabRoute
  '/words': typeof WordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/vocab': typeof VocabRoute
  '/words': typeof WordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/levels': typeof LevelsRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/vocab': typeof VocabRoute
  '/words': typeof WordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/levels'
    | '/practice'
    | '/progress'
    | '/vocab'
    | '/words'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/levels'
    | '/practice'
    | '/progress'
    | '/vocab'
    | '/words'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/levels'
    | '/practice'
    | '/progress'
    | '/vocab'
    | '/words'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LevelsRoute: typeof LevelsRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  VocabRoute: typeof VocabRoute
  WordsRoute: typeof WordsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab': {
      id: '/vocab'
      path: '/vocab'
      fullPath: '/vocab'
      preLoaderRoute: typeof VocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LevelsRoute: LevelsRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  VocabRoute: VocabRoute,
  WordsRoute: WordsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
